# Generated by Django 3.0.7 on 2020-06-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('notes', models.TextField()),
                ('timestamp', models.DateField()),
                ('projectId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Phases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('complete', models.BooleanField()),
                ('active', models.BooleanField()),
                ('lastupdated', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('complete', models.BooleanField()),
                ('status', models.BooleanField()),
                ('lastupdated', models.DateField()),
                ('company', models.TextField()),
            ],
        ),
    ]
