# Generated by Django 3.0.7 on 2020-06-22 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restautomatepm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='projectId',
            new_name='projectid',
        ),
    ]
