# Generated by Django 3.0.7 on 2020-06-22 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restautomatepm', '0002_auto_20200622_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='projectid',
            new_name='projectId',
        ),
    ]
