# Generated by Django 3.0.7 on 2020-06-23 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restautomatepm', '0003_auto_20200622_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='phases',
            name='projectId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
