# Generated by Django 3.0.7 on 2020-06-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restautomatepm', '0005_auto_20200623_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='projects',
            name='lastupdated',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
