# Generated by Django 3.0.7 on 2020-06-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restautomatepm', '0006_auto_20200623_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.TextField(blank=True),
        ),
    ]
