# Generated by Django 3.0.7 on 2020-06-23 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restautomatepm', '0007_auto_20200623_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='company',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='description',
        ),
    ]
