# Generated by Django 3.0.7 on 2020-06-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restautomatepm', '0008_auto_20200623_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='lastupdated',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='status',
        ),
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.TextField(),
        ),
    ]
