# Generated by Django 3.0.7 on 2020-06-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restautomatepm', '0011_projects_lastupdated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phases',
            name='description',
        ),
        migrations.AlterField(
            model_name='phases',
            name='projectId',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projects',
            name='lastupdated',
            field=models.DateField(),
        ),
    ]
