# Generated by Django 3.0.7 on 2020-06-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restautomatepm', '0012_auto_20200623_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='description',
        ),
        migrations.AlterField(
            model_name='log',
            name='projectId',
            field=models.IntegerField(default=0),
        ),
    ]
