# Generated by Django 3.0.7 on 2020-06-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restautomatepm', '0013_auto_20200623_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='description',
            field=models.TextField(default='..changed not recorded'),
        ),
    ]
