# Generated by Django 3.0.7 on 2020-06-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restautomatepm', '0014_log_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='phases',
            name='lastupdated',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='projects',
            name='lastupdated',
            field=models.DateTimeField(),
        ),
    ]
