# Generated by Django 3.0.7 on 2020-06-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restautomatepm', '0016_projects_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='status',
        ),
        migrations.AlterField(
            model_name='log',
            name='description',
            field=models.TextField(default='..change not recorded'),
        ),
    ]
